sonar.projectKey=daily_tasks_app
sonar.projectName=Daily Tasks App
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8
sonar.sources=src,app.py
sonar.tests=tests,assert_tests.py
sonar.python.version=3.10
sonar.exclusions=**/__pycache__/**,**/*.pyc,data/**
